# Generated by Django 3.1.7 on 2021-03-19 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_folder', models.BooleanField()),
                ('folder_name', models.CharField(blank=True, max_length=500, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.node')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('method', models.CharField(default='GET', max_length=100)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, choices=[('application/json', 'JSON'), ('application/xml', 'XML'), ('text/html', 'HTML'), ('text/plain', 'Text'), ('application/x-www-form-urlencoded', 'Urlencoded')], max_length=500, null=True)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('data_params', models.TextField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.node')),
            ],
        ),
    ]
