# Generated by Django 3.1.7 on 2021-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='content_type',
            field=models.CharField(blank=True, choices=[('application/json', 'JSON'), ('text/html', 'HTML'), ('text/plain', 'Text'), ('application/x-www-form-urlencoded', 'Urlencoded')], max_length=500, null=True),
        ),
    ]
