# Generated by Django 3.1.7 on 2021-04-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210408_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
