# Generated by Django 3.1.7 on 2021-04-10 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210408_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='revision',
        ),
        migrations.AddField(
            model_name='node',
            name='edited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
