# Generated by Django 3.1.7 on 2021-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210410_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
