# Generated by Django 3.1.7 on 2021-04-19 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_node_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='version',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='node',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 20, 0, 16, 649940)),
        ),
    ]
