# Generated by Django 3.2 on 2021-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_node_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
